# Numpy Array

In [18]:
import numpy as np
import pandas as pd

type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [19]:
#Upcasting:

In [20]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [21]:
#two dimensions

In [22]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [23]:
#Minimum dimensions 2:

In [24]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [25]:
#dtype

In [26]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [27]:
#Data-type consisting of more than one element:

In [28]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
pd.DataFrame(x)

a  b
0  1  2
1  3  4

In [39]:
type(x[1][0])

numpy.int16

In [13]:

#Creating an array from sub-classes:

In [17]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [29]:
np.mat('1 2; 3 4')

matrix([[1, 2, 3, 4]])

# numpy.asarray

In [16]:
#Convert the input to an array.

In [18]:
#Convert a list into an array:

In [27]:
 a = [1, 2]
type(a)

list

In [25]:
type(np.asarray(a)) 

numpy.ndarray

In [31]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [30]:
np.asarray((1,2))

numpy.ndarray

In [25]:
#If dtype is set, array is copied only if dtype does not match:

In [43]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [33]:
np.asarray([1,2]) is a

False

In [36]:
np.asarray([1,2])

array([1, 2])

In [34]:
np.asarray(a, dtype=np.float64) is a

False

In [29]:
# ndarray subclasses are not passed through

In [44]:
issubclass(np.matrix, np.ndarray)

True

In [40]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [41]:
np.asarray(a) is a

False

In [42]:
np.asanyarray(a) is a

True

In [43]:
np.array(a) is a

False

# numpy.asanyarray

In [44]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [45]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [46]:
np.asanyarray([1,2]) is a

False

In [47]:
np.array(a, copy=True)  

array([[1, 2]])

In [40]:
#Create an array x, with a reference y and a copy z:

In [49]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [51]:
y = x
y

array([1, 2, 3])

In [52]:
z = np.copy(x)
z

array([1, 2, 3])

In [54]:
y[0] = 100
y

array([100,   2,   3])

In [55]:
x

array([100,   2,   3])

In [56]:
id(x[0])

1873076661872

In [57]:
id(y[0])

1873076662032

In [58]:
id(x) 

1873065868064

In [59]:
id(y)

1873065868064

# numpy.fromfunction

In [58]:
#Construct an array by executing a function over each coordinate.

In [94]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [119]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [61]:
#Create a new 1-dimensional array from an iterable object.

In [68]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001B41BA19348>

In [69]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [64]:
#A new 1-D array initialized from text data in a string

In [101]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [102]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [79]:
# How to create create a record array from a (flat) list of arrays

In [71]:
x1=np.array([1,2,3,4])

In [72]:
x2=np.array(['a','dd','xyz','12'])

In [73]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [74]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [76]:
print(r[1]["d"])

2.0


In [130]:
x1[1]

2

In [140]:
d=np.array(list(zip(x1,x2,x3,x4)))
d
# list(zip(x1,x2,x3,x4))

array([['1', 'a', '1.1', '1.1'],
       ['2', 'dd', '2.0', '2.0'],
       ['3', 'xyz', '3.0', '3.0'],
       ['4', '12', '4.0', '4.0']], dtype='<U11')

# data types

In [120]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [121]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [122]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [95]:
c=[(1.5,2,3), (4,5,6)]
b = np.array(c)
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [127]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [128]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [129]:
list(range(50,-1,5))

[]

In [97]:
print("Numbers spaced apart by 2:",np.arange(50,-1,-2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2  0]


In [131]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [98]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [99]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,21)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


# Matrix creation

In [136]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [139]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [127]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [140]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [100]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [102]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [149]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [132]:
np.arange(3)

array([0, 1, 2])

In [80]:
np.arange(3.0)

array([0., 1., 2.])

In [81]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [82]:
np.arange(3,7,2)

array([3, 5])

In [150]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [103]:
np.linspace(2.0, 3.0, num=5, endpoint=False,retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [153]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [147]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [104]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [113]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])

In [155]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [115]:
#Extract a diagonal or construct a diagonal array.

In [112]:
x = np.arange(16).reshape((4,-1))

In [106]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
np.diag(x)

array([ 0,  5, 10, 15])

In [114]:
np.diag(x, k=3)

array([3])

In [183]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [115]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [122]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [180]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [116]:
np.diagflat([1,2,3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [125]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [119]:
np.tri(3, -1,dtype=int)

array([], shape=(3, 0), dtype=int32)

In [191]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [128]:
#return a Lower triangle of an array.

In [205]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [130]:
#return Upper triangle of an array.

In [206]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [197]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.79234365 0.26636652 0.84876143]
 [0.78766627 0.06627396 0.8829639 ]]


In [209]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.08550888  0.73651756  0.08329424]
 [ 0.75179279  0.42441618  0.47752353]
 [ 0.23835886  1.06582108 -0.01790105]
 [ 0.48190152 -0.24940656 -0.44992115]]


In [120]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 5

Random integer matrix


In [123]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[65 98 61 85]
 [11 47 87 63]
 [97  2 84  5]
 [43 63 33 24]]

20 samples drawn from a dice throw: [6 3 6 3 1 2 2 5 6 2 4 3 3 3 2 2 1 5 1 1]


# Reshaping

In [124]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c
b

array([[[15, 94, 46, 48, 98],
        [27,  9, 21,  5, 99],
        [55, 91, 49, 23, 29]],

       [[13, 65, 48, 72, 17],
        [ 5, 74,  8, 57,  1],
        [17,  8, 83, 57, 74]]])

In [125]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [126]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [15 94 46 48 98 27  9 21  5 99 55 91 49 23 29 13 65 48 72 17  5 74  8 57
  1 17  8 83 57 74] 
 --------------------

b looks like
 -------------------- 
 [[[15 94 46 48 98]
  [27  9 21  5 99]
  [55 91 49 23 29]]

 [[13 65 48 72 17]
  [ 5 74  8 57  1]
  [17  8 83 57 74]]] 
 --------------------

c looks like
 -------------------- 
 [[15 94 46 48 98]
 [27  9 21  5 99]
 [55 91 49 23 29]
 [13 65 48 72 17]
 [ 5 74  8 57  1]
 [17  8 83 57 74]] 
 --------------------


In [127]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [84 16 92 10  2 42 28 85 61 44]

Here is the sorted vector
 -------------------------------------------------- 
 [ 2 10 16 28 42 44 61 84 85 92]


In [134]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[10 31 70 77 93]
 [ 2  9 25 90 94]
 [ 4  8 33 68 75]
 [31 70 74 76 89]
 [ 4 42 58 82 82]]


array([[77, 31, 10, 93, 70],
       [ 2, 94,  9, 90, 25],
       [68, 75,  8, 33,  4],
       [31, 70, 89, 76, 74],
       [82, 42, 82,  4, 58]])

In [135]:
print("Max of a:", M.max())


Max of a: 94


In [136]:
M

array([[77, 31, 10, 93, 70],
       [ 2, 94,  9, 90, 25],
       [68, 75,  8, 33,  4],
       [31, 70, 89, 76, 74],
       [82, 42, 82,  4, 58]])

In [138]:
print("Max of a location:", M.argmax(axis= 1 ))
# print("Max of b location:", b.argmax())
# print("Max of c location:", b.argmax())

Max of a location: [3 1 1 2 0]


# Indexing and slicing

In [141]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [142]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [143]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [144]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [148]:
print("3 Elements from last backwards are:", arr[-1:6:-1])


3 Elements from last backwards are: [10  9  8  7]


In [165]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [64]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [152]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:1,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[11 32 53 64 37]
 [14 59 30 12 63]
 [47 27 30 34 43]]


array([[32, 64]])

In [153]:
mat[0:3,[1,3]]
mat

array([[11, 32, 53, 64, 37],
       [14, 59, 30, 12, 63],
       [47, 27, 30, 34, 43]])

In [155]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[0][0])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 11


array([[11, 32, 53, 64, 37],
       [14, 59, 30, 12, 63],
       [47, 27, 30, 34, 43]])

In [156]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 30

Row or column extract
----------------------


In [172]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [22 10 57 59 61]
Entire column at index 3: [92 88 59]


In [7]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[14 32]
 [62 27]]


In [156]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[77 69]
 [64 17]]


# Subseting

In [157]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[93 72 85 97 19]
 [51 89 95 31 34]
 [37 88 29 72 21]]


array([[ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [False,  True, False,  True, False]])

In [158]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [93 72 85 97 51 89 95 88 72]


# Slicing

In [159]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [160]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [161]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [162]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [163]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [21]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


Sliced matrix
[[11 12]
 [21 22]]


In [178]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


Change the sliced matrix
[[1000   12]
 [  21   22]]


In [22]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [166]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[6 7 1]
 [3 4 4]
 [5 6 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 8 7]
 [5 6 7]
 [7 5 7]]


In [167]:
mat1*mat2

array([[30, 56,  7],
       [15, 24, 28],
       [35, 30, 63]])

In [168]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 72  95  98]
 [ 63  68  77]
 [118 121 140]]


In [169]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [170]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[106 107 101]
 [103 104 104]
 [105 106 109]]


In [172]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[216 343   1]
 [ 27  64  64]
 [125 216 729]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[216 343   1]
 [ 27  64  64]
 [125 216 729]]


# Broadcasting

In [174]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [254]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [256]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [257]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [262]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [263]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [264]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [265]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 5 4]
 [1 7 3]
 [8 3 5]]

2nd Matrix of random single-digit numbers
------------
 [[4 8 6]
 [7 6 8]
 [4 6 5]]


In [266]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.23606798 2.        ]
 [1.         2.64575131 1.73205081]
 [2.82842712 1.73205081 2.23606798]]


In [267]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 1.48413159e+02 5.45981500e+01]
 [2.71828183e+00 1.09663316e+03 2.00855369e+01]
 [2.98095799e+03 2.00855369e+01 1.48413159e+02]]


In [173]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.77815125 0.84509804 0.        ]
 [0.47712125 0.60205999 0.60205999]
 [0.69897    0.77815125 0.95424251]]
[[6 7 1]
 [3 4 4]
 [5 6 9]]
[[5 8 7]
 [5 6 7]
 [7 5 7]]


In [174]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 7 1]
 [3 4 4]
 [5 1 2]]


array([[1, 7, 1],
       [3, 4, 4],
       [5, 1, 2]], dtype=int32)

In [186]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [207]:
A = np.linspace(0,12*np.pi,1001)


In [208]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])